version: "3.4"
services:
  erigon:
    image: "erigon.erigon.dnp.dappnode.eth:0.1.8"
    build:
      context: erigon
      args:
        UPSTREAM_VERSION: v2022.07.01
    ports:
      - "30315:30315/tcp"
      - "30315:30315/udp"
    volumes:
      - "data:/home/erigon/.local/share"
    environment:
      P2P_PORT: 30315
      ERIGON_EXTRA_OPTS: "--http.api=eth,erigon,web3,net,debug,trace,txpool"
    restart: unless-stopped
volumes:
  data: {}
